<a href="https://colab.research.google.com/github/graphtrek/tensorflow/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notbebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow

https://www.youtube.com/watch?v=tpCFfeUEGs8&list=WL&index=4&t=8295s

More specifically we're going to cover:
  * Introduction to tensors
  * Getting information from tensors
  * Manipulating tensors
  * Tensors & NumPy
  * Using @tf.function (a way to speed up your regular Python functions)
  * Using GPUs for TensorFlow or (TPUs)
  * Exercise to try yourself!

## Creating the first tensors (9. Creating our first tensors with TensorFlow)
* tf.constant

In [ ]:
# Import tensorflow
import tensorflow as tf
import numpy as np
import tensorflow_probability as tfp
print(tf.__version__)

2.6.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimension of a tensor (ndim stands for number as dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype=tf.float16)
                  
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]],
                      [[13,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far

  * Scalar: a single number
  * Vector: a 1 dimensional array
  * Matrix: a 2 dimensional array of numbers
  * Tensor: an n-dimensinal array of numbers  (where n can be any number, a 0 dimensional tensor is a scalar, a 1 dimensional tensor is a vector, a 2 dimensional tensor is a  matrix)

## Creating tensor with (10. Creating tensors with tf Variable)
* tf.Variable

In [ ]:
# Creating varibale tensors as above
changable_tensor = tf.Variable([10,7])
static_tensor = tf.constant([10,7])
changable_tensor, static_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Change an element in the tensor
changable_tensor[0] = 7

TypeError: ignored

In [ ]:
changable_tensor[0].assign(7)
changable_tensor[1].assign(77)

In [ ]:
static_tensor[0].assign(7)

## Creating random tensors (11. Creating random tensors)

Random tensors are tensors of some arbitrary size which contain random numbers
* T = tf.random.Generator.from_seed(42)
* T.normal(shape=(3,2))

In [ ]:
# Creating two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_1, random_2, random_2 == random_2

## Shuffle random tensors (12. Shuffling the order of tensors)
* tf.random.set_seed(42)
* tf.random.shuffle(T,seed=42) 

In [ ]:
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])

# https://www.tensorflow.org/api_docs/python/tf/random/shuffle
#tf.random.set_seed(42) # shuffle the same order every time if commented out get differnet results every time
not_shuffled, tf.random.shuffle(not_shuffled,seed=42) 

## Other ways to make tensors  (13. Creating tensors from NumPy arrays)
* tf.ones([3,2])
* 1tf.zeros([3,2])
* T = np.arange(1,25,1,np.int16)
* tf.constant(T,shape=(2,3,4)) 2\*3\*4 = 24 match T size

In [ ]:
one_tensor = tf.ones([3,2],tf.float16) # initiate a tensor filled with 1.
print("one_tensor", one_tensor.ndim)
one_tensor

In [ ]:
zero_tensor = tf.zeros([3,4],tf.float16)
zero_tensor

*italicized text*### Turn NumPy arrays into tensors

the main difference between the NumPy arrays and Tensorflow tensors that the tensors run on a GPU (much faster for numerical computing)

In [ ]:
import numpy as np
A = np.arange(1,25,1,np.int16)
A, tf.size(A)

In [ ]:
tf.constant(A,shape=(2,3,4))

In [ ]:
3*4*2

## Geeting information from tensors (14. Getting information from our tensors)
* T.shape, T.shape[-1]
* T.ndim
* tf.size(T), tf.size(T).numpy()
* T.dtype


In [ ]:
rank_4_tensor = tf.zeros(shape=(2,3,4,5))
rank_4_tensor

In [ ]:
print("DataType of every element:", rank_4_tensor.dtype)
print("Number of dimensions:",rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

## Indexing tensors (15. Indexing and expanding tensors)
* T[:2,:2,:2,:2], T[:,:,:,1]
* T[...,tf.newaxis]
* tf.expand_dims(T,-1)

In [ ]:
some_list = [1,2,3,4,5]
some_list

In [ ]:
some_list[:2]

In [ ]:
rank_4_tensor[:2,:2,:2,:2]

In [ ]:
rank_4_tensor[:,:,:,:]

In [ ]:
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor, rank_2_tensor.ndim, rank_2_tensor.shape

In [ ]:
rank_2_tensor[:,-1]

In [ ]:
rank_3_tensor = rank_2_tensor[...,tf.newaxis]
rank_3_tensor

In [ ]:
rank_5_tensor = rank_3_tensor[...,tf.newaxis,tf.newaxis]
rank_5_tensor

In [ ]:
tf.expand_dims(rank_2_tensor,-1)

## Manipulating tensors (16. Manipulating tensors with basic operations)
 * +,-,*,/
 * tf.multiply, tf.add, tf.subtract,tf.divide

In [ ]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10, tensor * 10, tensor - 10, tensor / 2 # the origanl tensor is not changed and element wise

In [ ]:
tf.multiply(tensor,10), tf.add(tensor,10), tf.subtract(tensor,1), tf.divide(tensor,2) # using the GPU 

## Matrix multiplication basic operations (17. Matrix multiplication part 1)
* tf.linalg.matmul(tensor,tensor), @ using the dot product


In [ ]:
tf.linalg.matmul(tensor,tensor), tensor @ tensor # using the dot product

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

## Matrix manipulation reshape (18. Matrix multiplication part 2)
* tf.reshape(T,shape=(2,3))
* tf.transpose(T)

In [ ]:
tf.reshape(Y,shape=(2,3)), Y, X @ tf.reshape(Y,shape=(2,3)) # @ = tf.matmul

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>)

In [ ]:
tf.matmul(X, tf.reshape(Y,shape=(2,3))), tf.matmul(Y,tf.reshape(X,shape=(2,3))) # differnt result !!!

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 39,  54,  69],
        [ 49,  68,  87],
        [ 59,  82, 105]], dtype=int32)>)

In [ ]:
X,tf.transpose(X), tf.reshape(X,shape=(2,3)) # transpose and resape are different because transpose move columns to rows

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

## Matrix multiplication the dot product (19. Matrix multiplication part 3)
* tf.tensordot(tf.transpose(X),Y,1), tf.matmul(tf.transpose(X),Y)

In [ ]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
tf.transpose(X), Y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X),Y,1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(X),Y,1), tf.matmul(tf.transpose(X),Y)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

In [ ]:
tf.matmul(X,tf.transpose(Y)) # perform tensor mainpulation with transpose

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y,shape=(2,3))) #perform tensor manipulation with reshape

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
print('Normal Y:\n' , Y ,'\n')
print('Reshaped Y:\n', tf.reshape(Y,shape=(2,3)), '\n')
print('Transposed Y:\n', tf.transpose(Y))

Normal Y:
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y:
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## Changing the datatype of tensors (20. Changing the datatype of tensors)
* tf.cast(T,dtype=tf.float16), tf.cast(T,dtype=tf.int16)

In [ ]:
tf.__version__

'2.6.0'

In [ ]:
B = tf.constant([1.7,7.4]) #dtype depends on the values float32 is the default
C = tf.constant([7,4]) #default dtype is int32
B,C

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>)

In [ ]:
tf.cast(B,dtype=tf.float16), tf.cast(C,dtype=tf.int16) # use less memory and runs faster 

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([7, 4], dtype=int16)>)

## Aggregating tensors (21. Aggregating tensors)
* tf.abs(T)
* tf.reduce_min(T), tf.reduce_max(T), tf.reduce_sum(T)
* tfp.stats.variance(tf.cast(T,tf.float16))
* tfp.stats.stddev(tf.cast(T,tf.float32))

In [ ]:
D = tf.constant([-7,-10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
E = tf.constant(np.random.randint(1,100,50))
E, tf.size(E), E.shape, E.ndim, tf.reduce_min(E), tf.reduce_max(E), tf.reduce_sum(E)

(<tf.Tensor: shape=(50,), dtype=int64, numpy=
 array([30, 34, 50, 45, 68, 52, 49, 90, 22, 83, 30, 91, 21, 89, 36, 30, 20,
        13, 80, 51, 68, 14, 43, 80, 41, 18, 22,  7, 73, 16, 77, 86,  4, 86,
        87, 99, 41,  6, 23, 76, 62,  6, 60, 27, 45, 67, 85, 18, 18, 49])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 TensorShape([50]),
 1,
 <tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2388>)

In [ ]:
tfp.stats.variance(tf.cast(E,tf.float16)), tfp.stats.stddev(tf.cast(E,tf.float32))

(<tf.Tensor: shape=(), dtype=float16, numpy=787.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=28.05677>)

## Tensor trableshooting (22. Tensor troubleshooting)
* tfp varinace and stddev in math lib
* tf.math.reduce_std(tf.cast(E, tf.float16))
* tf.math.reduce_variance(tf.cast(E,tf.float32))

In [ ]:
tf.math.reduce_std(E)

TypeError: ignored

In [ ]:
tf.math.reduce_std(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.05677>

In [ ]:
tf.math.reduce_variance(tf.cast(E,tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=787.1824>

## Find positional min and max (23. Find the positional min and max of a tensor)
* tf.random.set_seed(42)
* F = tf.random.uniform([50]) 
* tf.argmax(F), np.argmax(F), F[tf.argmax(F)], F[np.argmax(F)].numpy()
* assert tf.reduce_max(F) == F[tf.argmax(F)]

In [ ]:
tf.random.set_seed(42)
F = tf.random.uniform([50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(F), np.argmax(F), F[tf.argmax(F)], F[np.argmax(F)].numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 42,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 0.9671384)

In [ ]:
assert tf.reduce_max(F) == F[tf.argmax(F)]

## Squeezing tensor (24. Squeezing a tensor)
* tf.random.set_seed(42)
* T = tf.constant(tf.random.uniform([50]),shape=(1,1,1,50))
* tf.squeeze(T)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform([50]),shape=(1,1,1,50))

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>